name: Promote Python Package

on:
  repository_dispatch:
    types: [testresult]

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: ${{ vars.CLOUDSMITH_STAGING_REPO }}
  CLOUDSMITH_PRODUCTION_REPO: ${{ vars.CLOUDSMITH_PRODUCTION_REPO }}
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: 'example_package'
  TAG_NAME: "ready-for-production"

permissions:
  id-token: write
  contents: read

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Identify Syncronised Package and Tag
        run: |
          IDENT=${{ github.event.client_payload.identifier_perm }}
          if [ -z "$IDENT" ]; then
            echo "No identifier_perm provided by webhook."
            exit 1
          fi
          cloudsmith tag add \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}\
            "$IDENT" \
            ${{ env.TAG_NAME}}
            
      - name: Promote all ready-for-production packages
        run: |
          PKG_DATA=$(cloudsmith list package \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}\
            -q "tag:${{ env.TAG_NAME}}" -F json)

          IDS=$(echo "$PKG_DATA" | jq -r '.data[].identifier_perm')

          if [ -z "$IDS" ]; then
            echo "No packages tagged ${{ env.TAG_NAME}}."
            exit 0
          fi

          for ID in $IDS; do
          # Promote package using the identifier
          cloudsmith mv --yes \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
        shell: bash
